### ISSUE TITLE
Integration via HACS?

### ISSUE THREAD

**Issue by Lem0nz** [basvanrooten/hwl-api#13]
Been looking for an integration exactly like this one to combine our Home Wizard Lite (Smartwares) setup with Home Assistant.
However, unsure how to implement your code.
Is there a way to import it trough HACS?

Thanks

**Comment by basvanrooten** [comment]
Hi,

Thanks for showing interest! I'm currently on vacation, so I'll reach out to you when I'm back! I'm sure I can help you out :)

**Comment by basvanrooten** [comment]
Hi Lem0nz,

I've sent you a DM on FB Messenger, so if you still want help we can continue our conversation over there.
