### ISSUE TITLE
Smartplug / plug ID

### ISSUE THREAD

**Issue by poulenc1899** [basvanrooten/hwl-api#3]
Thank you for releasing this! Exactly what I was looking for. 

I'm a bit confused by the endpoint /api/act/smartplug/:smartPlugID/plug/:plugID. What constitutes the smartplug ID and plug ID? Using the registered plug IDs of the hub and plug I only get an error.

My request is in this format
`curl -H "Content-Type: application/json" -X POST -d '{"action":"on"}' http://192.168.1.6:3000/api/act/smartplug/[HUB ID]/plug/[PLUG ID]`

Thanks,
M

**Comment by basvanrooten** [comment]
Hi @poulenc1899!

In this project a plug is defined as a switchable entity (the actual 433mhz plug)

The smartplug is defined as the internet connected hub. Currently the API (quite unfortunately) doesn't support a GET on that entity, so here's a workaround to get the ID of the smartplug.

1. Use the `/api/test/session` endpoint to get a valid session token.
2. `curl --request GET --url https://plug.homewizard.com/plugs --header 'x-session-token: [SESSION TOKEN HERE]'`
You'll get the response from Home Wizard, containing your smartplug, with an array of devices (plugs).
3. Use the smartplugID and plugID in your request.

I've made a new ticket to include the smartplug in the `/api/plug` endpoint.

If you have any more questions regarding the API, feel free to ask them.

^_^

**Comment by poulenc1899** [comment]
Thank you for the super helpful response. It's all working now and I'm in automation heaven :)

**Comment by basvanrooten** [comment]
You're very welcome. Hope you enjoy :)
